# Generated by Django 5.2 on 2025-05-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_tune_description', models.TextField(blank=True, null=True)),
                ('modify_post_cta', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('other_posting_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('other_writing_style', models.CharField(blank=True, max_length=255, null=True)),
                ('other_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('other_job_description', models.CharField(blank=True, max_length=255, null=True)),
                ('content_types', models.ManyToManyField(blank=True, to='backend.contenttype')),
                ('industries', models.ManyToManyField(blank=True, to='backend.industry')),
                ('job_descriptions', models.ManyToManyField(blank=True, to='backend.jobdescription')),
                ('posting_goals', models.ManyToManyField(blank=True, to='backend.postinggoal')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpreference')),
                ('writing_styles', models.ManyToManyField(blank=True, to='backend.writingstyle')),
            ],
        ),
    ]
