# Generated by Django 5.2 on 2025-05-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_package_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferenceselection',
            name='other_content_type',
        ),
        migrations.RemoveField(
            model_name='userpreferenceselection',
            name='other_industry',
        ),
        migrations.RemoveField(
            model_name='userpreferenceselection',
            name='other_job_description',
        ),
        migrations.RemoveField(
            model_name='userpreferenceselection',
            name='other_posting_goal',
        ),
        migrations.RemoveField(
            model_name='userpreferenceselection',
            name='other_writing_style',
        ),
    ]
